import React, { createContext, useContext, useEffect, useState } from 'react'

const translations = {
  de: {
    'home.heroTitle': 'Entdecke leckere Rezepte bei',
    'home.heroSubtitle': 'Deine Rezepte, einfach geplant - schnell gekocht. Melde dich an, um eigene Rezepte zu sichern!',
    'home.signedIn': 'Du bist angemeldet',
    'home.goToHub': 'Zum Kitch N Break Hub',
    'home.latestRecipes': 'Aktuelle Rezepte',
    'home.loadingRecipes': 'Rezepte werden geladen...',
    'search.placeholder': 'Suche Rezepte',
    'auth.loginTitle': 'Jetzt Anmelden',
    'auth.registerTitle': 'Konto erstellen',
    'auth.namePlaceholder': 'Dein Name',
    'auth.emailPlaceholder': 'Email',
    'auth.passwordPlaceholder': 'Passwort',
    'auth.loginButton': 'Einloggen',
    'auth.registerButton': 'Registrieren',
    'auth.switchToLogin': 'Bereits ein Konto? Login',
    'auth.switchToRegister': 'Noch kein Konto? Registrieren',
    'nav.greeting': 'Hallo',
    'nav.recipesHub': 'Kitch N Break Hub',
    'nav.createRecipe': 'Rezept erstellen',
    'nav.logout': 'Abmelden',
    'create.heading': 'Rezept erstellen',
    'create.title': 'Neues Rezept',
    'create.authRequired': 'Bitte melde dich an, bevor du ein Rezept speicherst.',
    'create.authRequiredTitle': 'Anmeldung erforderlich',
    'create.authRequiredDescription': 'Melde dich an, damit dein Rezept direkt in deinem Dashboard erscheint.',
    'create.goToLogin': 'Zur Anmeldung',
    'create.backToDashboard': 'Zurück zum Dashboard',
    'create.titleLabel': 'Titel des Gerichts',
    'create.categoryLabel': 'Kategorie',
    'create.descriptionLabel': 'Zubereitung / Beschreibung',
    'create.save': 'Rezept speichern',
    'create.saving': 'Wird gespeichert...',
    'create.titleTooShort': 'Der Rezepttitel muss mindestens 3 Zeichen lang sein.',
    'create.saveError': 'Das Rezept konnte nicht gespeichert werden. Bitte versuche es noch einmal.',
    'create.descriptionPlaceholder': 'Schritt-für-Schritt Anleitung...',
    'category.Hauptgericht': 'Hauptgericht',
    'category.Vorspeise': 'Vorspeise',
    'category.Nachspeise': 'Nachspeise',
    'category.Snack': 'Snack',
    'category.Frühstück': 'Frühstück',
    'dashboard.title': 'Kitch N Break Hub',
    'dashboard.welcome': 'Willkommen, {name}. Deine Rezepte erscheinen hier direkt nach dem Speichern.',
    'dashboard.myRecipes': 'Eigene Rezepte',
    'dashboard.favorites': 'Favoriten',
    'dashboard.categories': 'Kategorien',
    'dashboard.noRecipes': 'Noch keine eigenen Rezepte',
    'dashboard.noRecipesDesc': 'Speichere dein erstes Rezept. Danach landest du automatisch wieder hier im Dashboard.',
    'dashboard.noRecipesFound': 'Keine Rezepte gefunden',
    'dashboard.switchViewOrFavorite': 'Wechsle die Ansicht oder markiere Rezepte als Favorit.',
    'dashboard.createdByYou': 'Von dir erstellt',
    'dashboard.findAgain': 'Zum Wiederfinden',
    'dashboard.inYourRecipes': 'In deinen Rezepten',
    'dashboard.loadingRecipes': 'Rezepte werden geladen...',
    'dashboard.loginRequiredTitle': 'Bitte anmelden',
    'dashboard.loginRequiredDescription': 'Dein Dashboard ist verfügbar, sobald du angemeldet bist.',
    'dashboard.goHome': 'Zur Startseite',
    'dashboard.newRecipe': 'Neues Rezept',
    'dashboard.ownRecipesTab': 'Eigene Rezepte',
    'dashboard.latestActivity': 'Letzte Aktivitäten',
    'dashboard.noActivity': 'Noch keine Aktivität. Dein erstes Rezept erscheint nach dem Speichern hier.',
    'dashboard.quickAccess': 'Schnellzugriff',
    'dashboard.createRecipe': 'Rezept erstellen',
    'dashboard.discoverRecipes': 'Rezepte entdecken',
    'dashboard.noDate': 'Kein Datum',
    'dashboard.noCategory': 'Ohne Kategorie',
    'dashboard.favoriteError': 'Favorit konnte nicht aktualisiert werden.',
    'dashboard.ownerOnly': 'Nur der Besitzer darf löschen.',
    'dashboard.deleteConfirm': 'Rezept löschen?',
    'dashboard.deleteError': 'Rezept konnte nicht gelöscht werden.',
    'card.view': 'Anzeigen',
    'card.favorite': 'Favorit',
    'card.edit': 'Bearbeiten',
    'card.delete': 'Löschen',
    'details.notFound': 'Rezept nicht gefunden',
    'details.back': 'Zurück',
    'details.ingredients': 'Zutaten',
    'details.preparation': 'Zubereitung',
    'details.reviews': 'Bewertungen',
    'details.rating': 'Bewertung:',
    'details.reviewPlaceholder': 'Deine Bewertung',
    'details.submitReview': 'Bewertung abgeben',
    'details.loadingReviews': 'Lade Bewertungen...',
    'details.noReviews': 'Keine Bewertungen',
    'details.anonymous': 'Anonym',
    'details.loginForReview': 'Bitte anmelden um eine Bewertung abzugeben.',
    'edit.loading': 'Lade...',
    'edit.heading': 'Rezept bearbeiten',
    'edit.titlePlaceholder': 'Titel',
    'edit.descriptionPlaceholder': 'Beschreibung',
    'edit.save': 'Speichern',
    'list.noResults': 'Keine Rezepte gefunden.'
  },
  en: {
    'home.heroTitle': 'Discover delicious recipes at',
    'home.heroSubtitle': 'Your recipes, simply planned and quickly cooked. Sign in to save your own recipes.',
    'home.signedIn': 'You are signed in',
    'home.goToHub': 'Go to Kitch N Break Hub',
    'home.latestRecipes': 'Latest recipes',
    'home.loadingRecipes': 'Loading recipes...',
    'search.placeholder': 'Search recipes or categories...',
    'auth.loginTitle': 'Sign in',
    'auth.registerTitle': 'Create account',
    'auth.namePlaceholder': 'Your name',
    'auth.emailPlaceholder': 'Email',
    'auth.passwordPlaceholder': 'Password',
    'auth.loginButton': 'Log in',
    'auth.registerButton': 'Register',
    'auth.switchToLogin': 'Already have an account? Log in',
    'auth.switchToRegister': 'No account yet? Register',
    'nav.greeting': 'Hi',
    'nav.recipesHub': 'Kitch N Break Hub',
    'nav.createRecipe': 'Create recipe',
    'nav.logout': 'Log out',
    'create.heading': 'Create recipe',
    'create.title': 'New recipe',
    'create.authRequired': 'Please sign in before saving a recipe.',
    'create.authRequiredTitle': 'Sign-in required',
    'create.authRequiredDescription': 'Sign in so your recipe appears directly in your dashboard.',
    'create.goToLogin': 'Go to sign in',
    'create.backToDashboard': 'Back to dashboard',
    'create.titleLabel': 'Dish title',
    'create.categoryLabel': 'Category',
    'create.descriptionLabel': 'Preparation / Description',
    'create.save': 'Save recipe',
    'create.saving': 'Saving...',
    'create.titleTooShort': 'The recipe title must be at least 3 characters long.',
    'create.saveError': 'The recipe could not be saved. Please try again.',
    'create.descriptionPlaceholder': 'Step-by-step instructions...',
    'category.Hauptgericht': 'Main course',
    'category.Vorspeise': 'Starter',
    'category.Nachspeise': 'Dessert',
    'category.Snack': 'Snack',
    'category.Frühstück': 'Breakfast',
    'dashboard.title': 'Kitch N Break Hub',
    'dashboard.welcome': 'Welcome, {name}. Your recipes appear here after saving.',
    'dashboard.myRecipes': 'My recipes',
    'dashboard.favorites': 'Favorites',
    'dashboard.categories': 'Categories',
    'dashboard.noRecipes': 'No own recipes yet',
    'dashboard.noRecipesDesc': 'Save your first recipe. You will return here afterwards.',
    'dashboard.noRecipesFound': 'No recipes found',
    'dashboard.switchViewOrFavorite': 'Switch views or mark recipes as favorites.',
    'dashboard.createdByYou': 'Created by you',
    'dashboard.findAgain': 'Easy to find again',
    'dashboard.inYourRecipes': 'In your recipes',
    'dashboard.loadingRecipes': 'Loading recipes...',
    'dashboard.loginRequiredTitle': 'Please sign in',
    'dashboard.loginRequiredDescription': 'Your dashboard is available once you are signed in.',
    'dashboard.goHome': 'Go to home',
    'dashboard.newRecipe': 'New recipe',
    'dashboard.ownRecipesTab': 'My recipes',
    'dashboard.latestActivity': 'Latest activity',
    'dashboard.noActivity': 'No activity yet. Your first recipe will appear here after saving.',
    'dashboard.quickAccess': 'Quick access',
    'dashboard.createRecipe': 'Create recipe',
    'dashboard.discoverRecipes': 'Discover recipes',
    'dashboard.noDate': 'No date',
    'dashboard.noCategory': 'No category',
    'dashboard.favoriteError': 'Favorite could not be updated.',
    'dashboard.ownerOnly': 'Only the owner can delete this recipe.',
    'dashboard.deleteConfirm': 'Delete recipe?',
    'dashboard.deleteError': 'Recipe could not be deleted.',
    'card.view': 'View',
    'card.favorite': 'Favorite',
    'card.edit': 'Edit',
    'card.delete': 'Delete',
    'details.notFound': 'Recipe not found',
    'details.back': 'Back',
    'details.ingredients': 'Ingredients',
    'details.preparation': 'Preparation',
    'details.reviews': 'Reviews',
    'details.rating': 'Rating:',
    'details.reviewPlaceholder': 'Your review',
    'details.submitReview': 'Submit review',
    'details.loadingReviews': 'Loading reviews...',
    'details.noReviews': 'No reviews',
    'details.anonymous': 'Anonymous',
    'details.loginForReview': 'Please sign in to leave a review.',
    'edit.loading': 'Loading...',
    'edit.heading': 'Edit recipe',
    'edit.titlePlaceholder': 'Title',
    'edit.descriptionPlaceholder': 'Description',
    'edit.save': 'Save',
    'list.noResults': 'No recipes found.'
  }
}

const LanguageContext = createContext()

export function LanguageProvider({ children }){
  const [lang, setLang] = useState(() => (typeof window !== 'undefined' && localStorage.getItem('lang')) || 'de')

  useEffect(()=>{
    if(typeof window !== 'undefined') localStorage.setItem('lang', lang)
  },[lang])

  function t(key, vars){
    const dict = translations[lang] || translations.de
    let str = dict[key] || key
    if(vars){
      Object.keys(vars).forEach(k => {
        str = str.replace(new RegExp(`{${k}}`, 'g'), vars[k])
      })
    }
    return str
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage(){
  return useContext(LanguageContext)
}

export default LanguageContext
